dist: trusty
language: java
sudo: false
jdk:
  - oraclejdk13
  - openjdk13
env:
  - NODE_VERSION="12"
before_install:
  - nvm --version
  - nvm install $NODE_VERSION
before_script:
  - npm --version
  - node --version
  - npm install
script:
  - npm test
notifications:
  slack: rustyhorde:qUn6626kqV2JaMsGUFLlNvJa
