language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
env:
  - NODE_VERSION="5.8" CC=clang CXX=clang++
  - NODE_VERSION="5.7" CC=clang CXX=clang++
  - NODE_VERSION="5.6" CC=clang CXX=clang++
  - NODE_VERSION="5.5" CC=clang CXX=clang++
  - NODE_VERSION="5.4" CC=clang CXX=clang++
  - NODE_VERSION="5.3" CC=clang CXX=clang++
  - NODE_VERSION="5.2" CC=clang CXX=clang++
  - NODE_VERSION="5.1" CC=clang CXX=clang++
  - NODE_VERSION="5.0" CC=clang CXX=clang++
  - NODE_VERSION="4.4" CC=clang CXX=clang++
  - NODE_VERSION="4.3" CC=clang CXX=clang++
  - NODE_VERSION="4.2" CC=clang CXX=clang++
  - NODE_VERSION="4.1" CC=clang CXX=clang++
  - NODE_VERSION="4.0" CC=clang CXX=clang++
  - NODE_VERSION="0.12"
  - NODE_VERSION="0.11"
  - NODE_VERSION="0.10"
before_install:
  - nvm --version
  - nvm install $NODE_VERSION
before_script:
  - npm --version
  - node --version
  - npm install
script:
  - npm test
notifications:
  slack: rustyhorde:qUn6626kqV2JaMsGUFLlNvJa
