language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
env:
  - NODE_VERSION="7.1" CC=clang CXX=clang++
  - NODE_VERSION="7.0" CC=clang CXX=clang++
  - NODE_VERSION="6.9.1" CC=clang CXX=clang++
  - NODE_VERSION="6.8.1" CC=clang CXX=clang++
  - NODE_VERSION="6.7" CC=clang CXX=clang++
  - NODE_VERSION="6.6" CC=clang CXX=clang++
  - NODE_VERSION="6.5" CC=clang CXX=clang++
  - NODE_VERSION="6.4" CC=clang CXX=clang++
  - NODE_VERSION="6.3.1" CC=clang CXX=clang++
  - NODE_VERSION="6.2.2" CC=clang CXX=clang++
  - NODE_VERSION="6.1" CC=clang CXX=clang++
  - NODE_VERSION="6.0" CC=clang CXX=clang++
  - NODE_VERSION="5.12" CC=clang CXX=clang++
  - NODE_VERSION="5.11.1" CC=clang CXX=clang++
  - NODE_VERSION="5.10.1" CC=clang CXX=clang++
  - NODE_VERSION="5.9.1" CC=clang CXX=clang++
  - NODE_VERSION="5.8" CC=clang CXX=clang++
  - NODE_VERSION="5.7.1" CC=clang CXX=clang++
  - NODE_VERSION="5.6" CC=clang CXX=clang++
  - NODE_VERSION="5.5" CC=clang CXX=clang++
  - NODE_VERSION="5.4.1" CC=clang CXX=clang++
  - NODE_VERSION="5.3" CC=clang CXX=clang++
  - NODE_VERSION="5.2" CC=clang CXX=clang++
  - NODE_VERSION="5.1.1" CC=clang CXX=clang++
  - NODE_VERSION="5.0" CC=clang CXX=clang++
  - NODE_VERSION="4.6.2" CC=clang CXX=clang++
  - NODE_VERSION="4.5" CC=clang CXX=clang++
  - NODE_VERSION="4.4.7" CC=clang CXX=clang++
  - NODE_VERSION="4.3.2" CC=clang CXX=clang++
  - NODE_VERSION="4.2.6" CC=clang CXX=clang++
  - NODE_VERSION="4.1.2" CC=clang CXX=clang++
  - NODE_VERSION="4.0" CC=clang CXX=clang++
  - NODE_VERSION="0.12"
  - NODE_VERSION="0.11"
  - NODE_VERSION="0.10"
before_install:
  - nvm --version
  - nvm install $NODE_VERSION
before_script:
  - npm --version
  - node --version
  - npm install
script:
  - npm test
notifications:
  slack: rustyhorde:qUn6626kqV2JaMsGUFLlNvJa
